### ISSUE TITLE
Logs missing for async requests that result in an error (i.e., 5xx server response)

### ISSUE THREAD

**Issue by matthewnessworthy** [bilfeldt/laravel-http-client-logger#36]
### Subject of the issue

When sending async requests, failures are not logged, only successful requests are logged

### Your environment

PHP 8.3, Laravel 11

### Steps to reproduce

Send an async request that results in a 5xx response and see no logs produced

### Expected behaviour

Logs should appear for async http requests that result in an error

### Actual behaviour

Logs do not appear for async http requests that result in an error

**Comment by bilfeldt** [comment]
@matthewnessworthy I cannot confirm that this is the case. Can you make a minimal code reproducing this?

**Comment by matthewnessworthy** [comment]
@bilfeldt my apologies, i had some bad error handling that was suppressing some errors
